using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LocumApp.Domain.Models;

/// <summary>
///     Base class for entities with common audit and identity properties.
/// </summary>
public abstract class BaseEntity
{
    /// <summary>
    ///     Primary key identifier. Auto-generated by the database.
    /// </summary>
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    [Column("id")] // Added Column attribute
    public int Id { get; set; }

    /// <summary>
    ///     User ID of the creator of the entity. Required.
    /// </summary>
    [Required]
    [Column("created_by_id")]
    public int CreatedById { get; set; } = 1;

    /// <summary>
    ///     UTC timestamp when the entity was created.
    ///     Defaults to <see cref="DateTime.UtcNow" /> if not explicitly set.
    /// </summary>
    [Column("created_at_utc")]
    public DateTime? CreatedAtUtc { get; set; }

    /// <summary>
    ///     User ID of the last user who updated the entity. Nullable.
    /// </summary>
    [Column("updated_by_id")]
    public int? UpdatedById { get; set; }

    /// <summary>
    ///     UTC timestamp when the entity was last updated.
    ///     Defaults to <see cref="DateTime.UtcNow" />.
    /// </summary>
    [Column("updated_at_utc")]
    public DateTime? UpdatedAtUtc { get; set; }

    /// <summary>
    ///     Flag to indicate if the entity is soft-deleted.
    /// </summary>
    [Column("is_deleted")]
    public bool IsDeleted { get; set; } = false;
}