using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LocumGQLGateway.Models;

/// <summary>
///     Base class for entities with common audit and identity properties.
/// </summary>
public abstract class BaseEntity
{
    private DateTime _createdAtUtc = DateTime.UtcNow;

    /// <summary>
    ///     Primary key identifier. Auto-generated by the database.
    /// </summary>
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    /// <summary>
    ///     User ID of the creator of the entity. Required.
    /// </summary>
    [Required]
    public int CreatedById { get; set; } = 1;
    
    /// <summary>
    /// Navigation property for the user who created the entity.
    /// </summary>
    [ForeignKey(nameof(CreatedById))]
    public User CreatedBy { get; set; } = null!;
    
    /// <summary>
    ///     UTC timestamp when the entity was created.
    ///     Defaults to <see cref="DateTime.UtcNow" /> if not explicitly set.
    /// </summary>
    public DateTime CreatedAtUtc
    {
        get => _createdAtUtc;
        set => _createdAtUtc = value == default ? DateTime.UtcNow : value;
    }

    /// <summary>
    ///     User ID of the last user who updated the entity. Nullable.
    /// </summary>
    public int? UpdatedById { get; set; }

    /// <summary>
    /// Navigation property for the user who last updated the entity.
    /// </summary>
    [ForeignKey(nameof(UpdatedById))]
    public User? UpdatedBy { get; set; }
    
    /// <summary>
    ///     UTC timestamp when the entity was last updated.
    ///     Defaults to <see cref="DateTime.UtcNow" />.
    /// </summary>
    public DateTime UpdatedAtUtc { get; set; } = DateTime.UtcNow;

    /// <summary>
    ///     Flag to indicate if the entity is soft-deleted.
    /// </summary>
    public bool IsDeleted { get; set; } = false;
}